### ISSUE TITLE
err when i try with bsc network

### ISSUE THREAD

**Issue by ducthanh200398** [umbracle/go-web3#122]
![image](https://user-images.githubusercontent.com/64213702/145332179-e7a67b9c-fc84-46f1-ae6f-1fb2b7716904.png)
![image](https://user-images.githubusercontent.com/64213702/145332207-bccd62e0-a18c-4d82-b584-58ded68cba35.png)

**Comment by lvlts** [comment]
looks like your environment variable is invalid. hardcoding the URL works and returns correctly. try this:

```
client, err := jsonrpc.NewClient("https://bsc-dataseed.binance.org/") 
```

**Comment by ferranbt** [comment]
Hi, as @lvlts pointed out, this might be an error on your env variable that is returning an error from the JSON-RPC request.
