### ISSUE TITLE
Increase best-effort encoding capabilities

### ISSUE THREAD

**Issue by darioAnongba** [umbracle/go-web3#130]
Hello,

First I want to say thank you for this library that is helping us a lot by using the `Encode` function. We were very surprised that this functionality was not available in go-ethereum and relieved that this package existed.

What we noticed using this package are 2 things that can be improved:

**Sending float64 as number**
 When passing arguments in JSON, the numbers are typed as `float64`. So if you are passing an `interface{}` that comes from JSON. The package will fail because `float64` is not accepted. This would be trivial to fix in the package (if you expect `int, int8, etc, uint, uint8...` and receive `float64`, just cast it into the correct type)
 
 **Sending addresses as strings**
When passing addresses in JSON, they are strings prefixed with "0x". The package does not work if it expects an address and receives a string. This would be trivial to fix in the package (if you expect `address` and receive string, just try to cast it into `Address`)

I can do a quick PR for these fixes

**Comment by ferranbt** [comment]
Hi @darioAnongba! Thank you for using the library. Indeed, one of the main goals to build this project was to improve a bit more the abi encoding functionalities in Go. Glad that you are finding it useful.

A PR with this weakly typed decoding would be fantastic.

**Comment by darioAnongba** [comment]
Ok I'll implement ASAP
