### ISSUE TITLE
undefined: fastrlp.MarshalRLP

### ISSUE THREAD

**Issue by fckveza** [umbracle/go-web3#137]
How to fix? 
![Screenshot_2022-01-12-18-06-38-75_84d3000e3f4017145260f7618db1d683](https://user-images.githubusercontent.com/36743311/149128949-67e3800c-c303-425a-81e3-4cd1664df09f.jpg)

**Comment by ferranbt** [comment]
Can you give me more context on this issue? When is this happening? Did you do ```go get ...```?
