### ISSUE TITLE
[question] transactions input decode or encode?

### ISSUE THREAD

**Issue by itcuihao** [umbracle/go-web3#144]
example:

```
input:
 0xa9059cbb0000000000000000000000003cd751e6b0078be393132286c442345e5dc496990000000000000000000000000000000000000000000000003b2118092395ec00

or

input: 

[]byte{0x7c, 0x2, 0x52, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0……}
```

How to transaction decode and encode?

**Comment by ferranbt** [comment]
Is this a transaction in RLP format? or the input/output of the call? Do you have the ABI?

**Comment by itcuihao** [comment]
> Is this a transaction in RLP format? or the input/output of the call? Do you have the ABI?

I use ` hex.EncodeToString` to resolve, temporarily give up decode.

**Comment by itcuihao** [comment]
Can I want to get transactions's trades and logs get this repo?

**Comment by itcuihao** [comment]
Hi, I use `trace, err := s.gethClient.Debug().TraceTransaction(block.Hash)`,  return err

```
{\"code\":-32601,\"message\":\"The method debug_traceTransaction does not exist/is not available\"}
```

Where did I get an error?
